### ISSUE TITLE
Why distinguish FUN and CTR?

### ISSUE THREAD

**Issue by lawcho** [Kindelia/HVM#147]
The [Core Language Overview](https://github.com/Kindelia/HVM/blob/master/HOW.md#hvms-core-language-overview) sends the message that "HVM functions are just constructors", so I was surprised to find that the implementation actually has separate FUN and CTR tags, e.g. here: https://github.com/Kindelia/HVM/blob/9b051c4cf312139a3d4909cedf30e4055fe1e4cb/src/runtime.rs#L204-L205

Is there any particular reason why these are kept separate rather than combined?

Everywhere I looked in the source code handles FUN and CTR similarly, so I experimentally [merged FUN and CTR](https://github.com/lawcho/HVM/tree/experiment/merge-fun-ctr), and the same tests still pass.

**Comment by VictorTaelin** [comment]
The only reason we distinguish CTR and FUN is for the DUP rule. Specifically,

```
let x = (Foo ...)
(Pair x x)
```

Will reduce to `(Pair (Foo ...) (Foo ...))` if it is a constructor, but will not reduce if it is a function. Semantically, both are equivalent and will wield the same results, yes, but cloning functions will break optimality and confluence on the underlying interaction net system that HVM emulates. That means merging CTR and FUN would cause terms to run asymptotically slower, and require exponentially more rewrites, than they do currently. This is for the same reason optimal λ-calculus evaluators do not clone applications. That is,

```
let y = (f x)
(Pair y y)
```

Is not a redex. On the interaction net view, the difference is what port is considered the main port. On FUN nodes, the main port is the leftmost strict argument. On CTR nodes, the main port is the port pointing to its parent. So, for example, on `(Map fn (Cons 1 ...))`, the main port of the `(Map ...)` node is the one pointing downwards to its 2nd field (the `Cons` node). As for the `(Cons ...)` node, the main port is the one connecting to its parent (the `Map` node).

Bonus / advanced note: HVM's model actually kind-of breaks confluence as a pragmatic optimization, since `FUN` nodes match its arguments simultaneously. If we didn't do that, each complete lhs->rhs reduction would require N rewrites, 1 for each redex. We save up a lot of time doing it in a single pass, and, in this case, is mostly inoffensive, since it doesn't usually cause duplicate work. Of course, if you want 100% interaction net theoretical fidelity, you can just break your rewrite rules to always have only 1 redex.

**Comment by lawcho** [comment]
Thanks for the great explanation!
