### ISSUE TITLE
HVM doesn't use normal order reduction.

### ISSUE THREAD

**Issue by danaugrs** [Kindelia/HVM#163]
Consider the HVM program below. What do you expect the output to be?

```
(Foo Bar) = A
(Foo B) = B
Bar = B

Main = (Foo Bar)
```

I expected the output to be `A`, but HVM outputs `B`.
This is a problem because it means HVM isn't using normal order reduction.
That means that there exist programs that can terminate but that will fail to terminate on HVM.
For example, if we add the rule `B = Bar` to the program above it will never terminate on HVM:

```
(Foo Bar) = A
(Foo B) = B
Bar = B
B = Bar

Main = (Foo Bar)
```

If possible, HVM should be revised to use normal order reduction.
In normal order reduction the outermost redex (reducible expression) is always reduced first.
In this case that's `(Foo Bar)`, which readily reduces to `A`.

**Comment by VictorTaelin** [comment]
That's not right! HVM does use normal order reduction. When you pattern-match an argument, HVM must reduce strict arguments to weak-head normal form in order to pattern-match, just like in Haskell. The issue is that, in your program, `Bar` isn't a constructor, it is a definition that evaluates to `B`, which itself evaluates to `Bar`, forming a loop. As such, if your program depends on reading the value of `Bar`, which is the case for `Foo Bar`, it will fail to halt, rightfully so. The same issue would happen on Haskell:

```haskell
data Foo = A deriving Show

foo :: Foo -> Int
foo A = 0

a :: Foo
a = b

b :: Foo
b = a

main :: IO ()
main = do
  print (foo a)
```

**Comment by danaugrs** [comment]
Thanks for the reply! Please consider the below HVM program:
```
(Foo (Bar 1)) = (A 1)
(Foo (B 1)) = (B 1)
(Bar 1) = (B 1)

Main = (Foo (Bar 1))
```
It's a constructor-only version of the original program I posted. As far as I can tell it has the same problem. HVM reduces `(Foo (Bar 1))` to `(B 1)` but in normal order reduction it should reduce to `(A 1)`, no? What am I missing?

**Comment by VictorTaelin** [comment]
Normal order evaluation doesn't mean you don't reduce anything; it means you reduce something when it is **needed**, which is the case here, since `Foo` pattern-matches on its first argument. As such, `(Foo (Bar 1))` will trigger a reduction of `(Bar 1)` to weak-head normal form, so it turns into `(Foo (B 1))`, which evaluates to `(A 1)`. Note that while this looks like a "constructor-only" version, it isn't, because you use `Bar` as both a constructor (in `(Foo (Bar 1)) = (A 1)`) and as a function (`(Bar 1) = (B 1)`). This isn't legal in Haskell (you can't make constructors compute), which is why we couldn't replicate it there, but the situation is exactly the same. HVM allows it because there is no need to forbid, but it does have the weird behavior you're seeing.
