### ISSUE TITLE
[Question] Kubernetes deployment?

### ISSUE THREAD

**Issue by giuliohome** [Kindelia/HVM#166]
Is there the option to deploy to a Kubernetes cluster? Do you plan to release a Helm Chart?

For example I see they can support also GPU among ather things: see [GKE](https://cloud.google.com/kubernetes-engine/docs/how-to/gpus) or [K8s](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/) docs. 

Would it make sense? As long as you say that it "[scales with added cores](https://twitter.com/VictorTaelin/status/1591959427363573767)", I would guess so...

**Comment by zicklag** [comment]
@giuliohome it depends on what you mean by deploying to a kubernetes cluster. I see two possible interpretations of what that could mean:

1. You want to actually create a distributed HVM computer that could run different threads, not just on a different CPU core, but on a totally different machine in a Kubernetes cluster.
2. You want to take an application that was written for the HVM, and deploy _it_ on a kubernetes cluster.

Considering possibility 1, I think that is probably out of scope for HVM. It seems like that would be a different project entirely, but that could possibly leverage HVM. Or maybe you're thinking of something like Kindelia, which could absolutely run on a Kubernetes cluster.

Considering possibility 2, that depends entirely on the app that you write. For instance, if you wrote a distributed database on HVM, you could deploy your database to Kubernetes, but the helm chart would be specific to your database, not generic to the HVM.

----

Having a Helm Chart for HVM, would be similar to having a Helm Chart for Java. It doesn't really make sense to have for Java, but you would have a Helm Chart for Keycloak, an application built on the Java VM.

**Comment by giuliohome** [comment]
Both 1 and 2 are very interesting answers. I said it was a question so, as such, I now close this because it is answered and I don't want to waste your time with a follow up. Anyway I also add a couple of questions, in case you have time and are willing to reply again.

1-part-a) "run different threads, not just on a different CPU core, but on a totally different machine in a Kubernetes cluster": yeah that was somehow a hidden goal of my question, but I unfortunately I see it's out of scope. Ok, fair enough (but yes, you understood where I was heading to)

1-part-b) "something like Kindelia": well, that's interesting, so... is there a Helm Chart to run Kindelia on a Kubernetes cluster? Or a link to a doc explaining how to deploy it to k8s? I'd be happy to read it, at least.

2-single) "an application that was written for the HVM": well, tbh, I was thinking that the benchmark in the [tweet](https://twitter.com/VictorTaelin/status/1591959427363573767?) of @VictorTaelin could be treated as such an application and I was thinking to see that benchmark deployed on k8s and possibly giving even greater results, the bigger the cluster. But maybe, before speaking about kubernetes, I should have asked if that benchmark could be containerized (e.g. in docker), otherwise I should have concluded that one has to run the benchmark in a classical VM and possibly add more cores to that VM. 

Thanks again for your great work and your kind replies!
Best,
Giulio

**Comment by zicklag** [comment]
> , I should have asked if that benchmark could be containerized (e.g. in docker), otherwise I should have concluded that one has to run the benchmark in a classical VM and possibly add more cores to that VM.

Ah, OK, I see. So I think you could do something like executing an app like a a compute benchmark across a Kubernetes cluster, but we'd need to build like distributed compute framework on top of HVM first. Something like the [Disco](https://github.com/discoproject/disco) project, except for HVM, maybe.

That could be a very interesting extension of the performance benefits we get from HVM on a single machine, but I don't know of any experiments/efforts in that direction yet.

You could absolutely Dockerize the benchmark today, but that would only allow you to compute it on one machine at a time, without some mechanism for each container to communicate with the other containers on the job that they are doing.

---

[Kindelia](https://github.com/kindelia/kindelia) is a blockchain that is designed for running decentralized programs that can modify the global blockchain state, but it isn't necessarily designed as a high-performance distributed compute engine.

There isn't a guide for running on Kubernetes, but the container and helm chart would probably be extremely simple, because Kindelia nodes essentially organize themselves I believe, after knowing an initial set of nodes to connect to.

This means that Dockerizing Kindelia would be a simple docker container that would build the rust program and then run `kindelia node start` as it's entrypoint.

You would want to additionally setup the container so that you could configure the initial peer list through environment variables in the container.

Then to put that into a helm chart you would just need to run a few nodes as the initial peer list, and then run any number of other containers that would connect to the initial peer list to get connected to the network initially. This second group of nodes could scale up as much as you want and I think it should "just work".

**Comment by steinerkelvin** [comment]
@zicklag is on point.

> There isn't a guide for running on Kubernetes, but the container and helm chart would probably be extremely simple, because Kindelia nodes essentially organize themselves I believe, after knowing an initial set of nodes to connect to.

I'm going to publish a Docker image for the Kindelia Chain node eventually, but yeah...

>it isn't necessarily designed as a high-performance distributed compute engine

it is out of scope scope here.

---

About point 1, it seems to be a natural path in the future of this tech. But it's on a very different level from what we have now. Being able to auto-distribute HVM computation is the dream.
