### ISSUE TITLE
Missing LICENSE file.

### ISSUE THREAD

**Issue by nmsmith** [Kindelia/HVM#190]
It is unclear whether this project is under an open source license. No `LICENSE` file has been committed.

**Comment by VictorTaelin** [comment]
HVM will always be open-source, but we're reviewing the most fit license. We will push it back once we have a decision.

**Comment by ararslan** [comment]
> No `LICENSE` file has been committed.

The project had been MIT-licensed but it seems the license was removed in https://github.com/Kindelia/HVM/commit/3b3a71f7863961a6112d1d0a38ad33d915b36eb2.

> we're reviewing the most fit license. We will push it back once we have a decision.

I'm not a lawyer but as I understand it, all existing code is still MIT-licensed and thus the license notice legally needs to be preserved; that's part of the terms of the MIT license. Future contributions may be licensed differently if the copyright holder so chooses, but existing code remains under the MIT license.

Without a license file at all, there's no indication of one's rights to use or even view the code. See also https://choosealicense.com/no-permission/, which notes the following regarding users' rights in the absence of a license:

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

This applies to any changes made after the linked commit, since prior commits are bound by the MIT license.

It's also worth noting for reference that the LLVM project and the Racket language have both undergone relicensing efforts recently which required explicit approval from all prior contributors to release their contributions under the new license. Whether HVM will need to do the same I can't say but it's something to look at.

**Comment by VictorTaelin** [comment]
Thank you for the concern. HVM is indeed MIT pre https://github.com/Kindelia/HVM/commit/3b3a71f7863961a6112d1d0a38ad33d915b36eb2; what is being discussed is the license regarding future updates. It will most likely still be MIT anyway, we just don't have a decision yet.

**Comment by ararslan** [comment]
Makes sense, thank you for clarifying. You may want to consider adding the original license text somewhere in the repository for compliance with the original license's terms, perhaps with a note that code contributed prior to https://github.com/Kindelia/HVM/commit/3b3a71f7863961a6112d1d0a38ad33d915b36eb2 is under that license. That may make the situation clearer for onlookers while the decision is being made.

All the best and thank you for making HVM!

**Comment by ksf** [comment]
You might want to consider UPL, [the Roc devs ended up switching to it](https://github.com/roc-lang/roc/issues/1199). tl;dr: MIT/BSD-style licenses don't give patent grants hence people go to Apache2 but that's incompatible with GPLv2 so they dual-license as MIT/Apache2 but that's complex and inelegant. UPL fixes that. The license is OSI and FSF approved, you can be sure that they had a *very* close look at any legal implications as it was written by Oracle lawyers.
