### ISSUE TITLE
A Bunch of Thoughts

### ISSUE THREAD

**Issue by andrewthad** [Kindelia/HVM#49]
These aren't problems with this implementation. They're just ideas that I wanted to dump down somewhere. Feel free to close this after reading it.

* [Compiling Without Continuations](https://www.microsoft.com/en-us/research/publication/compiling-without-continuations/) describes a way to extend lambda calculus with join points. In GHC, this is used internally, but the end-user is unable to explicitly request that a let-bound lambda be compiled to a join point. It can be nice to have this be explicit so that it is easier to tell if a function allocates. Is it possible to extend HVM's calculus compatible with join points? Is it desirable?
* This came up [on reddit](https://www.reddit.com/r/rust/comments/sh947t/hvm_a_nextgen_massively_parallel_betaoptimal/), but the idea of exposing mutable arrays with a linear interface is interesting.
* As an alternative to mutable arrays, just having immutable arrays, but small, no more than than 16 elements or so. Even with just small arrays, it's possible to build persistent arrays as a tree-like structure. But the small arrays, along with indexing and update functions, would need to be built in. GHC doesn't let you unpack an array into a data constructor. Maybe HVM could. There are a bunch of data structures that can use this to improve cache coherence.

**Comment by VictorTaelin** [comment]
I don't know anything about joint points, I'll need to read some examples. A comment I can make about continuations, specifically, is that HVM's runtime already supports them! There is no way to write them with the user-facing syntax, though, but the runtime is capable of computing these neatly, so adding a call-with-cc operation to HVM would be trivial.

Now, the last idea is really interesting, because we could actually have **mutable** arrays of 16 elements. That would fit very well with HVM. We could build bigger mutable arrays as trees of 16-tuples. So, for example, an array of 65536 elements could be represented as a tree with depth 4, updating a single element would be extremely fast (just 3 reads and 1 write), and the array could be lazily cloned like everything else. I think this would give us a "pure mutable array" that performs almost as well as C buffers.

**Comment by dumblob** [comment]
> Now, the last idea is really interesting, because we could actually have **mutable** arrays of 16 elements. That would fit very well with HVM. We could build bigger mutable arrays as trees of 16-tuples. So, for example, an array of 65536 elements could be represented as a tree with depth 4, updating a single element would be extremely fast (just 3 reads and 1 write), and the array could be lazily cloned like everything else. I think this would give us a "pure mutable array" that performs almost as well as C buffers.

Reminds me of https://github.com/josephg/jumprope-rs .

**Comment by andrewthad** [comment]
Thanks for the response! Closing.

**Comment by rigille** [comment]
i would really love to see something like relaxed radix balanced trees implemented
